#define MSG_LENGTH_MAX 256

//for group (everyone)
#define EVERYONE_MOOD_HIGH    (ID_EVERYONE + 1)
#define EVERYONE_MOOD_LOW     (ID_EVERYONE + 2)

//monitor & conductor
#define MONITOR_HELLO         (ID_MONITOR + 1)
#define MONITOR_WAKEUP        (ID_MONITOR + 2)
#define MONITOR_SLEEP         (ID_MONITOR + 3)

//actors
#define GAS_HELLO             (ID_GAS + 1)
#define GAS_SLEEPING          (ID_GAS + 2)
#define GAS_RING_RING_RING    (ID_GAS + 3)

#define TRUNK_HELLO           (ID_TRUNK + 1)
#define TRUNK_SLEEPING        (ID_TRUNK + 2)
#define TRUNK_SING            (ID_TRUNK + 3)

#define DRUM_HELLO            (ID_DRUM + 1)
#define DRUM_SLEEPING         (ID_DRUM + 2)
#define DRUM_TOMTOM           (ID_DRUM + 3)

#define FLOAT_HELLO           (ID_FLOAT + 1)
#define FLOAT_SLEEPING        (ID_FLOAT + 2)
#define FLOAT_FLY             (ID_FLOAT + 3)

#define REEL_HELLO            (ID_REEL + 1)
#define REEL_SLEEPING         (ID_REEL + 2)
#define REEL_TURN             (ID_REEL + 3)

#define SPEAK_A_HELLO         (ID_SPEAK_A + 1)
#define SPEAK_A_SLEEPING      (ID_SPEAK_A + 2)
#define SPEAK_A_TIC           (ID_SPEAK_A + 3)
#define SPEAK_A_TAC           (ID_SPEAK_A + 4)
#define SPEAK_A_TOE           (ID_SPEAK_A + 5)
#define SPEAK_A_SET_PINGPONG  (ID_SPEAK_A + 6)
#define SPEAK_A_SET_VOICES    (ID_SPEAK_A + 7)
#define SPEAK_A_SET_NATURE    (ID_SPEAK_A + 8)

#define SPEAK_B_HELLO         (ID_SPEAK_B + 1)
#define SPEAK_B_SLEEPING      (ID_SPEAK_B + 2)
#define SPEAK_B_TIC           (ID_SPEAK_B + 3)
#define SPEAK_B_TAC           (ID_SPEAK_B + 4)
#define SPEAK_B_TOE           (ID_SPEAK_B + 5)
#define SPEAK_B_SET_PINGPONG  (ID_SPEAK_B + 6)
#define SPEAK_B_SET_VOICES    (ID_SPEAK_B + 7)
#define SPEAK_B_SET_NATURE    (ID_SPEAK_B + 8)

#define SPEAK_C_HELLO         (ID_SPEAK_C + 1)
#define SPEAK_C_SLEEPING      (ID_SPEAK_C + 2)
#define SPEAK_C_TIC           (ID_SPEAK_C + 3)
#define SPEAK_C_TAC           (ID_SPEAK_C + 4)
#define SPEAK_C_TOE           (ID_SPEAK_C + 5)
#define SPEAK_C_SET_PINGPONG  (ID_SPEAK_C + 6)
#define SPEAK_C_SET_VOICES    (ID_SPEAK_C + 7)
#define SPEAK_C_SET_NATURE    (ID_SPEAK_C + 8)

#define SPEAK_D_HELLO         (ID_SPEAK_D + 1)
#define SPEAK_D_SLEEPING      (ID_SPEAK_D + 2)
#define SPEAK_D_TIC           (ID_SPEAK_D + 3)
#define SPEAK_D_TAC           (ID_SPEAK_D + 4)
#define SPEAK_D_TOE           (ID_SPEAK_D + 5)
#define SPEAK_D_SET_PINGPONG  (ID_SPEAK_D + 6)
#define SPEAK_D_SET_VOICES    (ID_SPEAK_D + 7)
#define SPEAK_D_SET_NATURE    (ID_SPEAK_D + 8)

#define SPEAK_E_HELLO         (ID_SPEAK_E + 1)
#define SPEAK_E_SLEEPING      (ID_SPEAK_E + 2)
#define SPEAK_E_TIC           (ID_SPEAK_E + 3)
#define SPEAK_E_TAC           (ID_SPEAK_E + 4)
#define SPEAK_E_TOE           (ID_SPEAK_E + 5)
#define SPEAK_E_SET_PINGPONG  (ID_SPEAK_E + 6)
#define SPEAK_E_SET_VOICES    (ID_SPEAK_E + 7)
#define SPEAK_E_SET_NATURE    (ID_SPEAK_E + 8)

#define SPEAK_F_HELLO         (ID_SPEAK_F + 1)
#define SPEAK_F_SLEEPING      (ID_SPEAK_F + 2)
#define SPEAK_F_TIC           (ID_SPEAK_F + 3)
#define SPEAK_F_TAC           (ID_SPEAK_F + 4)
#define SPEAK_F_TOE           (ID_SPEAK_F + 5)
#define SPEAK_F_SET_PINGPONG  (ID_SPEAK_F + 6)
#define SPEAK_F_SET_VOICES    (ID_SPEAK_F + 7)
#define SPEAK_F_SET_NATURE    (ID_SPEAK_F + 8)

//for group (all speakers)
#define SPEAKERS_HELLO        (ID_SPEAKERS + 1)
#define SPEAKERS_SLEEPING     (ID_SPEAKERS + 2)
#define SPEAKERS_TIC          (ID_SPEAKERS + 3)
#define SPEAKERS_TAC          (ID_SPEAKERS + 4)
#define SPEAKERS_TOE          (ID_SPEAKERS + 5)
#define SPEAKERS_SET_PINGPONG (ID_SPEAKERS + 6)
#define SPEAKERS_SET_VOICES   (ID_SPEAKERS + 7)
#define SPEAKERS_SET_NATURE   (ID_SPEAKERS + 8)
//status: leading (speakers)
#define SPEAKERS_LEADING      (ID_SPEAKERS + 80)
#define SPEAKERS_FOLLOWING    (ID_SPEAKERS + 81)
